//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMD.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.StagingEbayBatchImports = new HashSet<StagingEbayBatchImport>();
            this.StagingEbayBatchImports1 = new HashSet<StagingEbayBatchImport>();
            this.StagingEbayItems = new HashSet<StagingEbayItem>();
            this.StagingEbayItems1 = new HashSet<StagingEbayItem>();
            this.StagingEbayItems2 = new HashSet<StagingEbayItem>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string Address { get; set; }
        public string ImageName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> Package { get; set; }
        public string RegisterPayPalTxnID { get; set; }
        public Nullable<System.DateTime> RegisterPayPalDate { get; set; }
        public Nullable<double> PayPalAmount { get; set; }
        public Nullable<double> PayPalAmountAfterDeduct { get; set; }
        public string PayPalMisc { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<StagingEbayBatchImport> StagingEbayBatchImports { get; set; }
        public virtual ICollection<StagingEbayBatchImport> StagingEbayBatchImports1 { get; set; }
        public virtual ICollection<StagingEbayItem> StagingEbayItems { get; set; }
        public virtual ICollection<StagingEbayItem> StagingEbayItems1 { get; set; }
        public virtual ICollection<StagingEbayItem> StagingEbayItems2 { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
