//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMD.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataWarehouseFactSale
    {
        public int SaleId { get; set; }
        public Nullable<int> DateId { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        public virtual DataWarehouseDimComapany DataWarehouseDimComapany { get; set; }
        public virtual DataWarehouseDimDate DataWarehouseDimDate { get; set; }
        public virtual DataWarehouseDimProduct DataWarehouseDimProduct { get; set; }
        public virtual DataWarehouseDimProductType DataWarehouseDimProductType { get; set; }
    }
}
