//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMD.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataWarehouseDimDate
    {
        public DataWarehouseDimDate()
        {
            this.DataWarehouseFactSales = new HashSet<DataWarehouseFactSale>();
        }
    
        public int DateId { get; set; }
    
        public virtual ICollection<DataWarehouseFactSale> DataWarehouseFactSales { get; set; }
    }
}
