//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMD.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagingToyGraderBatchImport
    {
        public StagingToyGraderBatchImport()
        {
            this.StagingToyGraderItems = new HashSet<StagingToyGraderItem>();
        }
    
        public int ToyGraderBatchImporttId { get; set; }
        public Nullable<bool> InProcess { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> StartedOn { get; set; }
        public string CompletedOn { get; set; }
        public Nullable<int> Imported { get; set; }
        public Nullable<int> Failed { get; set; }
    
        public virtual ICollection<StagingToyGraderItem> StagingToyGraderItems { get; set; }
    }
}
