//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMD.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagingToyGraderItem
    {
        public StagingToyGraderItem()
        {
            this.StagingEbayItems = new HashSet<StagingEbayItem>();
        }
    
        public int ToyGraderItemId { get; set; }
        public Nullable<int> ToyGraderBatchImporttId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public string AfaSerial { get; set; }
        public Nullable<int> Blister { get; set; }
        public Nullable<int> Card { get; set; }
        public string Company { get; set; }
        public Nullable<System.DateTime> DateGraded { get; set; }
        public Nullable<int> Figure { get; set; }
        public Nullable<int> Grade { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Series { get; set; }
        public string Title { get; set; }
        public string Variation { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual ICollection<StagingEbayItem> StagingEbayItems { get; set; }
        public virtual StagingToyGraderBatchImport StagingToyGraderBatchImport { get; set; }
    }
}
