//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMD.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagingEbayItem
    {
        public int EbayItemtId { get; set; }
        public int EbayBatchImportId { get; set; }
        public Nullable<int> ToyGraderItemId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string DeletedBy { get; set; }
        public string Condition { get; set; }
        public string CountryCode { get; set; }
        public string GalleryURL { get; set; }
        public string GlobalId { get; set; }
        public string ItemId { get; set; }
        public Nullable<bool> ListingInfoBuyItNowAvailable { get; set; }
        public Nullable<decimal> ListingInfoBuyItNowPrice { get; set; }
        public Nullable<System.DateTime> ListingInfoEndTime { get; set; }
        public Nullable<bool> ListingInfoGift { get; set; }
        public string ListingInfoListingType { get; set; }
        public Nullable<System.DateTime> ListingInfoStartTime { get; set; }
        public string PrimaryCategory { get; set; }
        public string ProducitId { get; set; }
        public string SecondaryCategory { get; set; }
        public Nullable<bool> SellerInfoTopRatedSeller { get; set; }
        public Nullable<int> SellingStatusBidCount { get; set; }
        public Nullable<decimal> SellingStatusCurrentPrice { get; set; }
        public string SellingStatusSellingState { get; set; }
        public string SellingStatusTimeLeft { get; set; }
        public string StoreInfoStoreName { get; set; }
        public string StoreInfoStoreURL { get; set; }
        public string SubTitle { get; set; }
        public string Title { get; set; }
        public string ViewItemUrl { get; set; }
        public string AFASerial { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual StagingEbayBatchImport StagingEbayBatchImport { get; set; }
        public virtual StagingToyGraderItem StagingToyGraderItem { get; set; }
    }
}
