//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMD.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagingEbayBatchImport
    {
        public StagingEbayBatchImport()
        {
            this.StagingEbayItems = new HashSet<StagingEbayItem>();
        }
    
        public int EbayBatchImportId { get; set; }
        public bool InProcess { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> StartedOn { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public Nullable<int> TotalKeywordMatched { get; set; }
        public Nullable<int> ToBeProcessed { get; set; }
        public Nullable<int> Imported { get; set; }
        public Nullable<int> Failed { get; set; }
        public Nullable<int> Duplicates { get; set; }
        public Nullable<int> NoListingType { get; set; }
        public Nullable<int> Auctions { get; set; }
        public Nullable<int> AuctionsWithBIN { get; set; }
        public Nullable<int> Classified { get; set; }
        public Nullable<int> FixedPrice { get; set; }
        public Nullable<int> StoreInventory { get; set; }
        public Nullable<System.DateTime> EbayTimestamp { get; set; }
        public string EbayVersion { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual ICollection<StagingEbayItem> StagingEbayItems { get; set; }
    }
}
