CREATE TABLE [dbo].[StagingEbayItems] (
    [EbayItemtId]                  INT             IDENTITY (1, 1) NOT NULL,
    [EbayBatchImportId]            INT             NOT NULL,
    [ToyGraderItemId]              INT             NULL,
    [CreatedBy]                    NVARCHAR (128)  NOT NULL,
    [CreatedOn]                    DATETIME        CONSTRAINT [DF_STG_EBayItem_CreatedOn] DEFAULT (getutcdate()) NOT NULL,
    [ModifiedBy]                   NVARCHAR (128)  NULL,
    [ModifiedOn]                   DATETIME        CONSTRAINT [DF_STG_EBayItem_ModifiedOn] DEFAULT (getutcdate()) NULL,
    [Deleted]                      BIT             CONSTRAINT [DF_STG_EBayItem_Deleted] DEFAULT ((0)) NOT NULL,
    [DeletedOn]                    DATETIME        NULL,
    [DeletedBy]                    NVARCHAR (128)  NULL,
    [Condition]                    NVARCHAR (50)   NULL,
    [CountryCode]                  NVARCHAR (50)   NULL,
    [GalleryURL]                   NCHAR (2048)    NULL,
    [GlobalId]                     NVARCHAR (12)   NULL,
    [ItemId]                       NVARCHAR (19)   NOT NULL,
    [ListingInfoBuyItNowAvailable] BIT             NULL,
    [ListingInfoBuyItNowPrice]     MONEY           NULL,
    [ListingInfoEndTime]           DATETIME        NULL,
    [ListingInfoGift]              BIT             NULL,
    [ListingInfoListingType]       NVARCHAR (20)   NULL,
    [ListingInfoStartTime]         DATETIME        NULL,
    [PrimaryCategory]              NVARCHAR (30)   NULL,
    [ProducitId]                   NVARCHAR (50)   NULL,
    [SecondaryCategory]            NVARCHAR (30)   NULL,
    [SellerInfoTopRatedSeller]     BIT             NULL,
    [SellingStatusBidCount]        INT             NULL,
    [SellingStatusCurrentPrice]    MONEY           NULL,
    [SellingStatusSellingState]    NVARCHAR (20)   NULL,
    [SellingStatusTimeLeft]        NVARCHAR (30)   NULL,
    [StoreInfoStoreName]           NVARCHAR (200)  NULL,
    [StoreInfoStoreURL]            NVARCHAR (2048) NULL,
    [SubTitle]                     NVARCHAR (1024) NULL,
    [Title]                        NVARCHAR (1024) NULL,
    [ViewItemUrl]                  NVARCHAR (2048) NULL,
    [AFASerial]                    NVARCHAR (30)   NULL,
    CONSTRAINT [PK_STG_EBayItem] PRIMARY KEY CLUSTERED ([EbayItemtId] ASC),
    CONSTRAINT [FK_StagingEbayItems_AspNetUsers_CreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[AspNetUsers] ([Id]),
    CONSTRAINT [FK_StagingEbayItems_AspNetUsers_DeletedBy] FOREIGN KEY ([DeletedBy]) REFERENCES [dbo].[AspNetUsers] ([Id]),
    CONSTRAINT [FK_StagingEbayItems_AspNetUsers_ModifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[AspNetUsers] ([Id]),
    CONSTRAINT [FK_StagingEbayItems_StagingEbayBatchImports] FOREIGN KEY ([EbayBatchImportId]) REFERENCES [dbo].[StagingEbayBatchImports] ([EbayBatchImportId]),
    CONSTRAINT [FK_StagingEbayItems_StagingToyGraderItems] FOREIGN KEY ([ToyGraderItemId]) REFERENCES [dbo].[StagingToyGraderItems] ([ToyGraderItemId])
);





